### PR TITLE
Change postVersion to preVersion

### PR DESCRIPTION
**Pull request by elpete**
postVersion doesn't commit the changed location.  We don't want to give an example that doesn't do what we want!

### CODE REVIEW

**Comment by bdw429s** [comment]
The problem with `preVersion` is it reads the version before it's updated.  I think this may be an enhancement in CommandBox to change when the version interceptors run.  I tried to simplify from what NPM had because there's was very confusing, but perhaps we need a new interception point so you can intercept
1) before the version is bumped
2) after the version is bumped
3) after the tag is committed

**Comment by elpete** [comment]
Hmmm...In my testing it works fine, @bdw429s.

1__box__java_

**Comment by elpete** [comment]
Ah...I take it back.  Blast.

**Comment by elpete** [comment]
So, Brad, maybe something like a `preTag` and `postTag` endpoint?

Or, we could instead just suggest that people write their own `postVersion` tagging script:

```
{
  "scripts": {
    "postVersion": "package set location='elpete/cbmigrations#v`package version`' && !git tag v`package version`"
  }
}
```

The advantage to that is 1) no new interception point and 2) they specify the order of their scripts.  The disadvantage is it's hard to read.

**Comment by elpete** [comment]
And now after trying to make that work, I'm in favor of a `preTag` and `postTag` 😅

**Comment by bdw429s** [comment]
Lol, one of the reasons I didn't make any tag interception points initially was because I was seriously considering making the tagging bit a module that simply listened to `postVersion` to do its magic.  I was kind of thinking it would just be an optional add-on that wasn't really part of the core.  I ended up just baking it in because that's what npm did and I wanted people to be able to `!git push && publish` on `postVersion` and have it include the new tag as well.  Therefore I needed to guarantee the tagging was done before `postVersion`.

It's hard to guess the workflow people will choose though.  I think the main use cases I cared about was the ability for people to:
1) Run tests and abort the tagging process (Need to see if that even works-- I don't think I'm checking the return status of package scripts yet!)
2) Run final build stuff like an asset build pipeline, etc
3) Update the location AFTER the tagging (not an issue with npm, but required for CommandBox
4) Do final git push and publish to forgebox.

Of course, there's nothing keeping people from creating an ad-hoc script called "build" or something that just does all of that, but it seemed that in the npm world, many people triggered stuff off of their version bump.  Can you create a ticket with these use cases along with whatever else you can think of so we make sure what we do works for everything.  Feel free to try putting in the new interceptors.  Just register them in the `InterceptorService` at the top of the file and then announce it with whatever `intercptData` that makes sense.

**Comment by lmajano** [comment]
Please be aware, that tagging should happen after the `location` is set.
This way the tag contains the correct location and version information

Luis F. Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com

ColdBox Platform: http://www.coldbox.org
Linked In: http://www.linkedin.com/pub/3/731/483
Blog: http://www.luismajano.com
IECFUG Manager: http://www.iecfug.com
Social: twitter.com/lmajano facebook.com/lmajano

**Comment by bdw429s** [comment]
Yes, exactly.  The tag for that version should contain the final box.json for that version.  Also, another thing people use package scripts for in npm is to do stuff like replace the version numbers in their code-- kind of like what we use Jenkins for right now.  Any final modifications to the source code as part of the build should be able to be completed before we tag/commit.

**Pull request merged**
