### PR TITLE
corrected some typos in getting started guide

### PR DESCRIPTION
**Pull request by carehart**

### CODE REVIEW

**Comment by bdw429s** [comment]
Looks great Charlie.  Thanks!

**Comment by bdw429s** [comment]
Development is merged into master, the Gitbook has built and your changes are now live @carehart !
http://commandbox.ortusbooks.com/content/getting_started_guide.html

**Comment by carehart** [comment]
Thanks, and glad to see that it got pushed up to the master, and the book republished so fast, for the benefit of those who would come along and get it. :-) I was worried that it might be that there'd be some long time before such a change was pushed live.

But this begs a new question: in that I have such typo corrections to propose for about every chapter (no offense intended by that), how would you like me to handle them? We might think I should do them all as one pull, commit, and push, to keep it easy to handle, but a problem is that it's possible I could get side-tracked in the midst of them, and might then end up sitting on them again for some time, which would be too bad.

So I'd think it better for me to push changes as soon as I'm done with a session of them (like after an hour's work), whether that's one or a few chapters, since it could be days before I may get a chance to work on the docs again. But I may well find I'd have another chunk of time even later that same day to work on them again. :-)

So the question is how you would want them pushed up. As you'd noted in an earlier comment on the other pull request, this is different from coding pushes, where you may typically need to test things, etc. and may not want too many pushes (especially to different files) too frequently, as it could be a challenge to test them. 

But since these merely require you to look over the few changes and confirm they are acceptable typo corrections, it would seem it should go fast (as indeed it did this morning).

So I guess I'm asking: do you have any preference for how I can best get these changes up to you? Anything you either do or do not want me to do?

Finally, I also have some "suggestions" to propose, but I am going to save them for last, as those could require consideration and perhaps talk among the authors about whether they are acceptable. So I am focusing first on clear typo's, all in the hopes that the docs puts its best foot forward. :-)

**Comment by bdw429s** [comment]
Thanks for being willing to help contribute more changes!  Honestly, you can send over as many fixes as you like on whatever schedule you want.  Merging them is literally as simple as be clicking a big green button on the Github site labeled "merge" so it's really no more or less work either way.  I would suggest just sending over what you have as you do it.  When it comes to the GitBooks, i just do a quick eyeball scan on the diff tab to make sure everything looks kosher.

The Gibook automatically rebuilds any time I merge changes into master (it's a pretty slick deal).  The only time I don't merge right away into master is when I'm preparing for a new release of CommandBox.  In that case, I'll update the development branch for the new release and wait to merge until we go live.  That shouldn't affect your efforts though-- any changes will make it into the book with the next merge to master.  

The only thing you need to be aware of is to occasionally merge from the main repo into yours so you keep up to date of changes that others make.  Your Git repo most likely has created a `origin` remote that points to your fork on Github as well as an `upstream` remote that points to the original repo that you forked.  Before you do any work, you'll want to merge `upstream/development` into your local `development` branch so you're up to date.

**Pull request merged**
