### PR TITLE
update folder example

### PR DESCRIPTION
**Pull request by sfeldkamp**
Didn't test the Windows example.

### CODE REVIEW

**Comment by bdw429s** [comment]
@sfeldkamp Is there a reason for this update?  The `endpoint:` prefix is unneeded in any scenario where CommandBox can automatically detect what you wanted.  And in the case of file and folder endpoints, so long as the installation ID is a valid directory or file path, it will work. 

We could add an explicit example, but I still want to recommend the "simple" and easier version in the docs.  FWIW, `github` is the other endpoint we detect by convention (`org/user#committish`)

**Comment by sfeldkamp** [comment]
I didn't think it was working.  I added dev-dependency folder to box.json as 

```
"devDependencies": {
	"commandbox-cfformat": "^0.17.5",
	"testbox": "/Users/sethfeldkamp/testbox/"
}
```

When I ran `install` I received the following error.

```
CommandBox:coldfusion> install
 × | Installing ALL dependencies   |------------------------------------------   | √ | Installing package [forgebox:commandbox-cfformat@^0.17.5]   | × | Installing package [forgebox:testbox@/Users/sethfeldkamp/testbox/]
   |   |---------------------------------------------------------------------------
   |   | Verifying package 'testbox' in forgebox, please wait...
   |   |---------------------------------------------------------------------------


ERROR (@build.version@+@build.number@)

Version [/Users/sethfeldkamp/testbox/] not found for package [testbox].

Available versions are [ 4.6.0-snapshot, 4.5.0+5, 4.5.0-snapshot, 4.4.0+456, 4.4.0-snapshot, 4.3.1+436, 4.3.1-snapshot, 4.3.0-snapshot, 4.2.1+400, 4.2.0+395, 4.2.0-snapshot, 4.1.0+384, 4.1.0-snapshot, 4.0.0+372, 4.0.0-snapshot, 3.3.0-snapshot, 3.2.0+356, 3.2.0-snapshot, 3.1.0+339, 3.1.0-snapshot, 3.0.0+305, 3.0.0-snapshot, 2.9.0-snapshot, 2.8.0+191, 2.8.0-snapshot, 2.7.0+167, 2.7.0-snapshot, 2.6.0+156, 2.6.0-snapshot, 2.5.0+107, 2.5.0-snapshot, 2.4.0+80, 2.4.0-snapshot, 2.3.0, 2.2.0, 2.1.0, 2.0.0]
```

Then I ran `install ~/testbox --saveDev`.  It worked and installed the dev dependency from my local folder in box.json as...

```
"devDependencies":{
        "commandbox-cfformat":"^0.17.5",
        "testbox":"folder:/Users/sethfeldkamp/testbox/"
    },
```

So I thought, based on the error, and the way that the CLI wrote the configuration into box.json that the docs were out of date.

**Comment by bdw429s** [comment]
Ahh, you just found a bug that only affected *nix :) Having the path in there directly works fine on Windows and apparently you're the first person to ever try it on a Mac, lol.  To be honest, not a lot of people use the file and folder endpoints.  I reproduced the bug in a Docker container and I believe I have it fixed now. on the bleeding edge  
https://ortussolutions.atlassian.net/browse/COMMANDBOX-1494

Feel free to still update the examples to show both methods if you like.

**Comment by sfeldkamp** [comment]
If the un-prefixed version will soon be working, I'm content to leave the documentation as is.  Using the CLI to install did work and is probably the more common case anyway.

**Pull request closed without merging**
