### PR TITLE
Corrected a few typos

### PR DESCRIPTION
**Pull request by carehart**

### CODE REVIEW

**Comment by bdw429s** [comment]
Thanks Charlie!  Can you please send this to our development branch?

**Comment by carehart** [comment]
Thanks. So let me clarify, this is my first contribution to any open source project. There was a lot I struggled with initially, based on both github itself, and tools. :-)

So to be clear, are you saying that you did merge these changes into the master? It seemed so, as I did a compare.

And are you saying that for future ones I should instead send to development? Or am I misreading things and the changes I sent are NOT yet in the master, and you need me to re-send them to development first?

Sorry for the lame newbie questions. I’d been sitting on these doc corrections since Devobjective, when I was given a hard-copy of the  book, and had read it on the flight home, finding the typo’s. It was the inertia of getting started (with github, and the tools) that kept me from contributing at all. I just happened to have a good open junk of time today for the first time in a long time.

I will welcome any guidance you have at all on doing things right/better. :-)

/charlie

PS One other question: about these emails, I see that they show up on my github account display. Are they public to all in the project (or everyone) or are they private and between you and me? Thanks.

**Comment by bdw429s** [comment]
Hi Charlie, no worries.  it's always a little confusing the first time.  These messages are public.  Replying to the E-mail will automatically post them for you.  As you see the actual address you reply to is a github.com.  it basically posts it to the issue and also forwards a copy to me.

I did not merge anything yet.  If you think you see the changes on master, you may be looking at your fork instead of the upstream project.  Different people use different Git flows, but for any Ortus product, all changes are always made in our "development" branch so any pulls should always be directed there.  Then we merge from development into master once tested.  (There's not really much testing involved with a Gitbook though)  

In this particular case master and development are the same (I just merged them earlier today), but generally speaking you want to make the changes in the corresponding branch in your fork (development), or better yet, a branch off of development.  In this case you can probably just resubmit the pull but choose "development" as the branch that you are sending the pull to on our side.  You'll probably want to either merge your master branch into your development branch or pull the upstream development branch once the new request is pulled just so your repo is out of sync.

If you haven't seen it, I have a complete guide on sending a pull request that covers this and more here:  (It has ColdBox in the title, but it really applies to any of our projects, and honeslty almost any Git project anywhere)
http://blog.coldbox.org/blog/how-to-submit-pull-requests-to-the-coldbox-platform

Please ask though if you have more questions.

**Comment by carehart** [comment]
OK, thanks. I had noticed that the reply address was one on github.com, yes. And I'd found the conversation on the web site as well. I just didn't know if that was perhaps still only between us (shown only to me because I'd logged in). Thanks for clarifying that it's public, and that's fine.

And thanks for clarifying that I was indeed misreading things when I mistakenly thought my comparison was to the "real" master when apparently it was my fork of it, Just one more thing to get used to in the tools. I happened to be using giteye, rather than github destkop--or the command line. I hoped I'd get started with a gui and then graduate later to the cmd line, specifically hoping it would help me avoid such newb mistakes! :-)

And I appreciate your guidance there on how to rectify the mistake. Will start over, doing things the right way (and since I changed only the one file so far, it will be easy to save and recover that work, then re-commmit it). This is in fact why I tried pushing just the changes to this first file, to get used to the "right way" of doing things.)

Finally, thanks for the link to the blog post, and for the post itself! Should be just what I need, but I appreciate your willingness to offer added help if needed.

**Pull request closed without merging**
